on: push
name: Publish tft file to http webserver
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u $UPLOAD_USER:$UPLOAD_PASSWORD --upload-file HMI/nspanel.tft $UPLOAD_URL 