on: push
name: Publish tft file to http webserver
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u ${{secrets.UPLOAD_USER}}:${{secrets.UPLOAD_PASSWORD}} --upload-file HMI/nspanel.tft ${{secrets.UPLOAD_URL}}