on: push
name: Publish tft file to http webserver
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u ${{secrets.UPLOAD_USER}}:${{secrets.UPLOAD_PASSWORD}} -i -X POST -H "Content-Type: multipart/form-data" -F "data=@HMI/nspanel.tft" -F "git_hash=$GITHUB_SHA" ${{secrets.UPLOAD_URL}}