name: nextion2text

on:
  pull_request:
    paths:
      - HMI/nspanel.HMI
  push:
    branches:
      - main
    paths:
      - HMI/nspanel.HMI

jobs:
  gen-nextion-to-text:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Get last commit message
      id: last-commit-message
      run: |
        echo "::set-output name=msg::$(git log -1 --pretty=%s)"

    - name: Run nextion2text
      run: |
        cd HMI
        wget https://raw.githubusercontent.com/joBr99/Nextion2Text/linux/Nextion2Text.py
        python Nextion2Text.py -s -d -p -p visual -i nspanel.HMI -o n2t-out

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ steps.last-commit-message.outputs.msg }} (add nextion2text)
        file_pattern: HMI/n2t-out/*.txt
